# Generated by Django 4.2.3 on 2024-03-09 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CabApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSC_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_place', models.CharField(blank=True, max_length=150, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('guest', models.CharField(blank=True, max_length=150, null=True)),
                ('time_of_arrival', models.TimeField(blank=True, null=True)),
                ('kilometers', models.FloatField(blank=True, default=0.0, null=True)),
                ('toll', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking', models.FloatField(blank=True, default=0.0, null=True)),
                ('entrance', models.FloatField(blank=True, default=0.0, null=True)),
                ('guide_fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('advance', models.FloatField(blank=True, default=0.0, null=True)),
                ('debit', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CabApp.driver')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
