# Generated by Django 4.2.3 on 2024-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0003_tsc_form_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='bill_qr',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
