# Generated by Django 4.2.3 on 2024-03-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0005_customer_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='ending_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='extra_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='fixed_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='other_charges',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='starting_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='trip_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='TSC_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('Trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CabApp.tsc_form')),
            ],
        ),
    ]
