# Generated by Django 4.2.3 on 2024-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0006_tsc_form_ending_km_tsc_form_extra_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsc_form',
            name='debit',
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='total_trip_expense',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
