# Generated by Django 4.2.3 on 2024-03-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0007_remove_tsc_form_debit_tsc_form_total_trip_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='trip_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
