# Generated by Django 4.2.3 on 2024-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0008_tsc_form_trip_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='permit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='trip_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
