# Generated by Django 4.2.3 on 2024-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0009_tsc_form_permit_tsc_form_trip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='max_kilometer',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='trip_extra_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='trip_fixed_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
