# Generated by Django 4.2.3 on 2024-04-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0010_tsc_form_max_kilometer_tsc_form_trip_extra_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRideHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CabApp.tsc_form')),
            ],
        ),
    ]
