# Generated by Django 4.2.3 on 2024-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0011_tripridehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsc_form',
            name='extra_hour_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='fixed_hour_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='max_hour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tsc_form',
            name='trip_charge_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
