# Generated by Django 4.2.3 on 2024-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabApp', '0013_alter_tripridehours_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripridehours',
            name='date',
        ),
        migrations.AlterField(
            model_name='tripridehours',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripridehours',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
